### ISSUE TITLE
Building it

### ISSUE THREAD

**Issue by kisiseldwarf** [Liareth/BG3ModPackager#1]
Hi !
I'm aware that there won't be much support for this repository, but still I find that it is awesome work and I would want to use it.
Could you please tell me how to build all this code to have the .exe you use in the readme ?
I'm fairly new to modding but I'm really motivated.

Thanks !

(I don't know how to contact you so I'm using github issues... apologies).

**Comment by Liareth** [comment]
Just install Visual Studio and compile! Easy peasy. I've created a release which has the binaries: https://github.com/Liareth/BG3ModPackager/releases/tag/v1

**Comment by kisiseldwarf** [comment]
Thank you a lot for your help and your reactivity, you keep me going ! :)
